### PR TITLE
Cart page

### PR DESCRIPTION
**Pull request by aayushjain-code**

### CODE REVIEW

**Comment by aayushjain-code** [comment]
https://priceless-davinci-82ecca.netlify.app/

**Review by MayankKumar10 — APPROVED** [review]
LGTM you can merge it

**Review by MuskanChhatrasal — APPROVED** [review]
Increase little bit of font-size. 
Else LGTM!! You can merge it.

**Comment by MayankKumar10** [comment]
> Increase little bit of font-size. Else LGTM!! You can merge it.

Okay  I'll do that, Thank you

**Pull request merged**
